name: build-test

on:
  schedule:
    - cron: '0 0 * * *'

  push:
    branches:
      - 'main'

  workflow_dispatch:
 
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  # if: github.event_name == 'push' || github.event_name == 'pull_request'
  test:
    uses: ./.github/workflows/test.yml
    with:
      # The name of the image to test.
      dockerfile: 'Dockerfile'
      image_name: helix-proxy
      version: ${{ vars.VERSION }}
      p4logdir: ${{ vars.P4PLOGDIR }}
      p4home: ${{ vars.P4HOME }}
    secrets: inherit