name: build-test

on:
  schedule:
    - cron: '0 0 * * 1'

  push:
    branches:
      - 'main'
    paths:
      - 'build/Dockerfile'

  workflow_dispatch:
 
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  # if: github.event_name == 'push' || github.event_name == 'pull_request'
  test:
    uses: ./.github/workflows/test.yml
    with:
      # The name of the image to test.
      docker_files_name: 'Dockerfile'
    secrets: inherit