name: build-develop

on:
  schedule:
    - cron: '0 0 1 * *'
  
  workflow_dispatch:
 
jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  # if: github.event_name == 'push' || github.event_name == 'pull_request'
  test:
    uses: ./.github/workflows/test.yml
    with:
      # The name of the image to test.
      dockerfile: 'Dockerfile'
      image_name: 'helix-proxy'
      version: ${{ vars.VERSION }}
      p4logdir: ${{ vars.P4PLOGDIR }}
      p4home: ${{ vars.P4HOME }}
    secrets: inherit

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  # TAG_SUFFIX="nightly-$(date +'%Y%m%d')"
  push:
    uses: ./.github/workflows/publish.yml
    needs: test
    with:
      # The name of the image to push.
      dockerfile: 'Dockerfile'
      image_name: 'helix-proxy'
      version: ${{ vars.VERSION }}
      p4logdir: ${{ vars.P4PLOGDIR }}
      p4home: ${{ vars.P4HOME }}
    secrets: inherit
