name: test

on:
  workflow_call:
    inputs:
      dockerfile:
        required: true
        type: string
      image_name:
        required: true
        type: string
      version:
        required: true
        type: string
      p4logdir:
        required: true
        type: string
      p4home:
        required: true
        type: string

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: |
          docker build \
          -t $GITHUB_WORKFLOW \
          --build-arg USER=${{ secrets.USER }} \
          --build-arg PASSWD=${{ secrets.PASSWD }} \
          --build-arg VERSION=${{ inputs.version }} \
          --build-arg P4PLOGDIR=${{ inputs.p4logdir }} \
          --build-arg P4HOME=${{ inputs.p4home }} \
          -f ./build/${{ inputs.dockerfile }} ./build
